// src/components/Checkbox.vue
<template>
    <div class="checkbox" :class="{'checkbox-active': active}">
        {{ $t(`settings.${locale.split('.')[0]}.items.${locale.substring(locale.indexOf('.') + 1)}`) }}

        <div class="checkbox-mark" @click="updateSetting">
            <img src="../assets/svgs/checkmark.svg" />
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import Configs from '../ts/Configs';

export default defineComponent({
    props: ['locale', 'prop'],

    data: () => ({
        active: false
    }),

    created()
    {
        Configs.get(this.prop).then((active) => this.active = active as boolean);
    },

    methods: {
        updateSetting()
        {
            this.active = !this.active;

            Configs.set(this.prop, this.active);
        }
    }
});
</script>

<style src="../sass/components/checkbox.sass" lang="sass"></style>

// src/components/Checkbox.svelte
<script lang="ts">
    import { _ } from 'svelte-i18n';

    export let active: boolean = false;

    export let prop: string = '';
    export let lang: string = '';

    import Checkmark from '../assets/svgs/checkmark.svg';

    import Configs from '../ts/Configs';

    Configs.get(prop).then((value) => active = value as boolean);

    function updateCheckbox()
    {
        active = !active;

        Configs.set(prop, active);
    }
</script>

<div class="checkbox" class:checkbox-active={active}>
    { $_(lang) }

    <div class="checkbox-mark" on:click={updateCheckbox}>
        <!-- svelte-ignore a11y-missing-attribute -->
        <img src={Checkmark} />
    </div>
</div>
